// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { mockSupabase } from '@/lib/mock-supabase';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Use real Supabase if keys are provided, otherwise fallback to Standalone (Mock) Mode
const useMock = !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY || SUPABASE_URL === "your-supabase-url";

if (useMock) {
  console.warn("Supabase keys missing or invalid. Running in Standalone (Mock) Mode. Data will be saved to LocalStorage.");
}

export const supabase = useMock 
  ? (mockSupabase as any)
  : createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    });